#!/bin/env zsh

function g {
  if [[ $# -gt 0 ]]; then
    if [[ ("$1" == "wt" || "$1" == "worktree") && ("$2" == "cd" || "$2" == "rm") && -n "$3" ]]; then
      local worktree_path=$(command git worktree list | awk -v name="$3" '$0 ~ name {print $1; exit}')
      if [[ -z "$worktree_path" ]]; then
        echo "Worktree '$3' not found" >&2
        return 1
      fi
      [[ "$2" == "cd" ]] && cd "$worktree_path" || command git worktree remove "$worktree_path"
    else
      git "$@"
    fi
  else
    git status
  fi
}
