let g:mapleader=" "

source $XDG_CONFIG_HOME/vim/options.vim
source $XDG_CONFIG_HOME/vim/autocmds.vim
source $XDG_CONFIG_HOME/vim/keymaps.vim
source $XDG_CONFIG_HOME/vim/tabline.vim
source $XDG_CONFIG_HOME/vim/session.vim
source $XDG_CONFIG_HOME/vim/tmux.vim
source $XDG_CONFIG_HOME/vim/quickfix.vim
source $XDG_CONFIG_HOME/vim/arglist.vim
source $XDG_CONFIG_HOME/vim/recent.vim
source $XDG_CONFIG_HOME/vim/findgrep.vim
source $XDG_CONFIG_HOME/vim/netrw.vim
source $XDG_CONFIG_HOME/vim/git.vim

if !has("nvim")
  source $XDG_CONFIG_HOME/vim/colorscheme.vim
endif

if has('persistent_undo')
  let target_path=has("nvim") ? fnameescape(stdpath('state') . '/undo') : expand('~/.vim/undo')
  if !isdirectory(target_path)
    call mkdir(target_path, "p", 0700)
  endif
  let &undodir=target_path
  set undofile
  set undolevels=10000
  set undoreload=100000
endif

augroup vimrcEx
  autocmd!
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
augroup END

" Local config
if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif

nnoremap <silent> <esc> :noh<CR>

packadd! cfilter
