let g:mapleader=" "

source $XDG_CONFIG_HOME/vim/options.vim
source $XDG_CONFIG_HOME/vim/autocmds.vim
source $XDG_CONFIG_HOME/vim/keymaps.vim
source $XDG_CONFIG_HOME/vim/tabline.vim
source $XDG_CONFIG_HOME/vim/session.vim
source $XDG_CONFIG_HOME/vim/quickfix.vim
source $XDG_CONFIG_HOME/vim/arglist.vim
source $XDG_CONFIG_HOME/vim/recent.vim
source $XDG_CONFIG_HOME/vim/findgrep.vim
source $XDG_CONFIG_HOME/vim/netrw.vim
source $XDG_CONFIG_HOME/vim/git.vim
source $XDG_CONFIG_HOME/vim/colorscheme.vim

if has('persistent_undo')
  let s:target_path=expand('~') .. '/.vim/undo'
  if !isdirectory(s:target_path)
    call mkdir(s:target_path, "p", 0700)
  endif
  set undofile
  set undolevels=10000
  let &undodir=s:target_path
endif

" Local config
if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif
