let g:mapleader=" "

source $XDG_CONFIG_HOME/vim/vimrc.options
source $XDG_CONFIG_HOME/vim/vimrc.autocmds
source $XDG_CONFIG_HOME/vim/vimrc.keymaps
source $XDG_CONFIG_HOME/vim/vimrc.tabline
source $XDG_CONFIG_HOME/vim/vimrc.session
source $XDG_CONFIG_HOME/vim/vimrc.tmux
source $XDG_CONFIG_HOME/vim/vimrc.quickfix
source $XDG_CONFIG_HOME/vim/vimrc.arglist

if !has("nvim")
  source $XDG_CONFIG_HOME/vim/vimrc.netrw
  source $XDG_CONFIG_HOME/vim/vimrc.colorscheme
endif

if has('persistent_undo')
  let target_path=has("nvim") ? fnameescape(stdpath('state') . '/undo') : expand('~/.vim/undo')
  if !isdirectory(target_path)
    call mkdir(target_path, "p", 0700)
  endif
  let &undodir=target_path
  set undofile
  set undolevels=10000
  set undoreload=100000
endif

augroup vimrcEx
  autocmd!
  autocmd BufReadPost *
    \ if &ft != 'gitcommit' && line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
augroup END

" Local config
if filereadable($HOME . "/.vimrc.local")
  source ~/.vimrc.local
endif

nnoremap <esc> :noh<CR>

packadd! cfilter

" Search
nnoremap <leader>/ :silent! grep! 
nnoremap <leader>? :silent! grepadd! 
augroup AutoOpenQfAfterGrepAdd
  autocmd!
  autocmd QuickFixCmdPost grep,grepadd copen
augroup END
