require("config.options")
require("config.keymaps")
require("config.autocmds")

require("config.icons")
require("config.netrw")

require("config.theme")
require("config.editor")
require("config.picker")
require("config.blink")
require("config.session")
require("config.git")
require("config.mason")
require("config.lsp")
require("config.lua")
require("config.dap")
require("config.treesitter")
require("config.formatter")
require("config.linter")
require("config.undo")
require("config.tabline")
require("config.quickfix")
require("config.diff")
require("config.copilot")
require("config.surround")
require("config.helm")
