source $XDG_CONFIG_HOME/vim/config/editor/session.vim
source $XDG_CONFIG_HOME/vim/config/editor/quickfix.vim
source $XDG_CONFIG_HOME/vim/config/editor/arglist.vim
source $XDG_CONFIG_HOME/vim/config/editor/recent.vim
source $XDG_CONFIG_HOME/vim/config/editor/findgrep.vim
source $XDG_CONFIG_HOME/vim/config/editor/netrw.vim
source $XDG_CONFIG_HOME/vim/config/editor/git.vim
source $XDG_CONFIG_HOME/vim/config/editor/make.vim
source $XDG_CONFIG_HOME/vim/config/editor/winpick.vim
